# Generated by Django 5.0.6 on 2024-08-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
